-- Starting rows for a fresh database. Safe to run more than once.
-- Paper trading only. No account ids and no live session state.

INSERT INTO public.bot_status (id, enabled, trading_mode, execution_mode, shutdown_requested)
VALUES (1, false, 'paper', 'ibkr', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.settings (
  id,
  max_rsi,
  watchlist,
  risk_profile,
  trading_mode,
  entry_ema_gate,
  max_daily_loss,
  max_spread_pct,
  risk_per_trade,
  watchlist_pool,
  account_capital,
  min_share_price,
  benchmark_symbol,
  loss_cut_enabled,
  max_hold_minutes,
  min_hold_minutes,
  min_volume_ratio,
  watchlist_active,
  max_position_size,
  min_dollar_volume,
  max_open_positions,
  confirmation_cycles,
  profit_take_enabled,
  confirmation_seconds,
  stop_loss_percentage,
  loss_cut_max_fraction,
  loss_cut_min_fraction,
  watchlist_active_size,
  loss_cut_min_band_hits,
  minimum_jev_confidence,
  take_profit_percentage,
  jev_sell_exit_threshold,
  signal_record_threshold,
  profit_take_max_fraction,
  profit_take_min_fraction,
  reentry_cooldown_minutes,
  profit_take_min_band_hits,
  watchlist_rotation_enabled,
  loss_cut_band_window_cycles,
  loss_cut_jev_sell_threshold,
  max_entries_per_symbol_per_day,
  profit_take_band_window_cycles,
  profit_take_jev_sell_threshold,
  rotation_min_session_change_pct,
  watchlist_max_swaps_per_rotation,
  watchlist_rotation_interval_minutes
) VALUES (
  1,
  75,
  ARRAY['NVDA', 'AAPL', 'MSFT', 'META', 'GOOGL', 'AMZN', 'TSLA', 'AMD', 'AVGO']::text[],
  'medium',
  'paper',
  'ema_9',
  10000,
  0.0015,
  2500,
  ARRAY['NVDA', 'AAPL', 'MSFT', 'AMZN', 'AVGO', 'META', 'TSLA', 'GOOGL', 'NFLX', 'COST', 'AMD', 'CSCO', 'TMUS', 'PEP', 'INTU', 'AMAT', 'ISRG', 'TXN', 'BKNG', 'QCOM', 'AMGN', 'HON', 'ADP', 'ADI', 'MU', 'PANW', 'LRCX', 'KLAC', 'APP', 'PLTR']::text[],
  1000000,
  5,
  'QQQ',
  true,
  0,
  5,
  0.5,
  ARRAY['ADP', 'AMZN', 'MU', 'PLTR', 'KLAC', 'NFLX', 'APP', 'AMD', 'TXN', 'MSFT', 'GOOGL', 'TSLA']::text[],
  5000,
  250000,
  6,
  1,
  true,
  15,
  0.009,
  0.9,
  0.7,
  12,
  3,
  0.74,
  0.015,
  0.98,
  0.65,
  0.99,
  0.65,
  10,
  3,
  true,
  10,
  0,
  3,
  10,
  0.7,
  0,
  3,
  15
)
ON CONFLICT (id) DO NOTHING;
