import type { Settings } from "@/lib/types/database";

export function settingsFixture(overrides: Partial<Settings> = {}): Settings {
  return {
    id: 1,
    trading_mode: "paper",
    minimum_jev_confidence: 0.8,
    signal_record_threshold: 0.5,
    risk_per_trade: 1,
    max_position_size: 100,
    max_daily_loss: 10,
    max_open_positions: 5,
    stop_loss_percentage: 0.01,
    take_profit_percentage: 0.02,
    max_hold_minutes: 0,
    min_hold_minutes: 15,
    jev_sell_exit_threshold: 0.95,
    reentry_cooldown_minutes: 45,
    confirmation_cycles: 2,
    confirmation_seconds: 30,
    min_volume_ratio: 0,
    min_share_price: 20,
    min_dollar_volume: 250_000,
    account_capital: 1000,
    risk_sync_equity: null,
    watchlist: ["BABA", "VALE", "EEM"],
    watchlist_core: ["NVDA", "AAPL", "EEM"],
    watchlist_dynamic_enabled: true,
    watchlist_dynamic_size: 5,
    watchlist_min_buy: 0.6,
    watchlist_refresh_minutes: 30,
    benchmark_symbol: "EEM",
    watchlist_jev_rankings: [],
    watchlist_screener_ran_at: "2026-01-10T15:00:00Z",
    watchlist_pins: [],
    watchlist_dismissed: [],
    demotion_exits_enabled: true,
    demotion_max_hold_ratio: 0.5,
    demotion_jev_sell_on_loss: true,
    demotion_jev_sell_max_loss_pct: 0.02,
    demotion_force_exit: false,
    profit_take_enabled: true,
    profit_take_min_fraction: 0.7,
    profit_take_max_fraction: 0.8,
    em_universe_synced_at: null,
    em_universe_source: null,
    updated_at: "",
    ...overrides,
  };
}
