import type { Settings } from "@/lib/types/database";

export function settingsFixture(overrides: Partial<Settings> = {}): Settings {
  return {
    id: 1,
    trading_mode: "paper",
    minimum_jev_confidence: 0.85,
    signal_record_threshold: 0.8,
    risk_per_trade: 2.5,
    max_position_size: 250,
    max_daily_loss: 10,
    max_open_positions: 2,
    stop_loss_percentage: 0.01,
    take_profit_percentage: 0.015,
    max_hold_minutes: 100,
    min_hold_minutes: 15,
    jev_sell_exit_threshold: 0.95,
    reentry_cooldown_minutes: 45,
    confirmation_cycles: 2,
    confirmation_seconds: 30,
    min_volume_ratio: 0.5,
    min_share_price: 20,
    min_dollar_volume: 250_000,
    account_capital: 1000,
    risk_sync_equity: 1000,
    watchlist: ["BABA", "VALE", "NVDA"],
    benchmark_symbol: "",
    watchlist_pool: [],
    watchlist_active: [],
    watchlist_rotation_enabled: false,
    watchlist_active_size: 12,
    watchlist_rotation_interval_minutes: 15,
    watchlist_max_swaps_per_rotation: 2,
    watchlist_last_rotation_note: "",
    entry_blocked_symbols: [],
    profit_take_enabled: false,
    profit_take_min_fraction: 0.7,
    profit_take_max_fraction: 0.8,
    profit_take_min_band_hits: 3,
    profit_take_band_window_cycles: 10,
    profit_take_jev_sell_threshold: 0.7,
    updated_at: "2026-01-10T15:00:00Z",
    ...overrides,
  };
}
